name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: RUSTFLAGS="-D warnings" cargo test --verbose
    - name: Build release
      run: RUSTFLAGS="-D warnings" cargo build --release
  bypass_cache:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: perf nocache
        run: cargo build --release && ./bypass_cache_perf.sh nocache
      - name: perf standard
        run: cargo build --release && ./bypass_cache_perf.sh standard